// admin/src/app/layouts/layout.component.ts
import { Component } from '@angular/core';
import { SidebarComponent } from './sidebar.component';
import { RouterOutlet } from '@angular/router';

@Component({
  imports: [
    SidebarComponent,
    RouterOutlet
  ],
  selector: 'app-layout',
  template: `
    <div className="min-h-screen flex flex-col">
      <header class="bg-red-600 p-4 text-white">
        <h1 class="text-xl font-bold">Mi Aplicación</h1>
      </header>
      <div class="flex flex-1">
        <app-sidebar></app-sidebar>
        <main class="flex-1 p-4">
          <router-outlet></router-outlet>
        </main>
      </div>
      <footer class="bg-red-600 p-4 text-white text-center">
        © 2025 Gestor de proyectos
      </footer>
    </div>
  `,
  styles: []
})
export class LayoutComponent {}

// app/src/layouts/Layout.tsx
import React from 'react';
import { Outlet } from 'react-router-dom';
import Sidebar from './SideBar';

const Layout: React.FC = () => {
  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="bg-blue-600 p-4 text-white">
        <h1 className="text-xl font-bold">Mi Aplicación</h1>
      </header>
      <div className="flex flex-1">
        {/* Sidebar */}
        <Sidebar />
        {/* Contenido principal */}
        <main className="flex-1 p-4">
          <Outlet />
        </main>
      </div>
      {/* Footer */}
      <footer className="bg-blue-600 p-4 text-white text-center">
        © 2025 Gestor de proyectos
      </footer>
    </div>
  );
};

export default Layout;
